// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvxqekfiqbuvwaupbcjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2eHFla2ZpcWJ1dndhdXBiY2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDU5MzQsImV4cCI6MjA2ODg4MTkzNH0.KUlEFVHB-R9aLGU7_gKwoZ6M6Sh5QshSyH7HAPR1PSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});